## **Experiment No : 14**
### **Data Selection, Cleaning & Wrangling**

### **Step 1: Import Libraries**

In [ ]:
import pandas as pd
import numpy as np

### **Step 2: Load Dataset**

In [ ]:
from google.colab import files
import io

try:
    print("Please upload the 'mental_health.csv' file:")
    uploaded = files.upload()

    if 'mental_health.csv' in uploaded:
        df = pd.read_csv(io.BytesIO(uploaded['mental_health.csv']))
        print("Dataset 'mental_health.csv' loaded successfully.")
        df.head()
    else:
        print("Warning: 'mental_health.csv' was not among the uploaded files. Please ensure you upload the correct file.")
        df = None # Ensure df is not defined if file not found
except Exception as e:
    print(f"An error occurred during file upload or reading: {e}")
    df = None

Please upload the 'mental_health.csv' file:

Saving mental_health.csv to mental_health.csv
Dataset 'mental_health.csv' loaded successfully.

The dataset is loaded using pandas. The head() function displays the first 5 rows to understand the structure of the dataset.

### **Step 3: Data Selection**
The dataset mental_health.csv contains 2000 records related to mental health factors such as screen time, sleep, stress, and lifestyle habits.
It is selected to analyze how lifestyle affects mental health conditions like depression, anxiety, and burnout.
### **Step 4: Understand Dataset**

In [ ]:
df.info()
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 18 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Person_ID                 2000 non-null   int64
 1   Age                       2000 non-null   int64
 2   Gender                    2000 non-null   object
 3   Occupation                2000 non-null   object
 4   Daily_Screen_Time         2000 non-null   float64
 5   Social_Media_Usage        2000 non-null   float64
 6   Night_Usage               2000 non-null   int64
 7   Sleep_Hours               2000 non-null   float64
 8   Stress_Level              2000 non-null   int64
 9   Work_Study_Hours          2000 non-null   float64
 10  Physical_Activity         2000 non-null   object
 11  Social_Interaction_Score  2000 non-null   int64
 12  Caffeine_Intake           2000 non-null   int64
 13  Smoking                   2000 non-null   int64
 14  Alcohol                   2000 non-null   int64
 15  Depression                2000 non-null   int64
 16  Anxiety                   2000 non-null   int64
 17  Burnout                   2000 non-null   int64
dtypes: float64(4), int64(11), object(3)
memory usage: 281.4+ KB

,Person_ID,Age,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
count,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.00000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000,2000.000000
mean,1000.500000,37.694000,6.943150,4.436400,0.489500,6.00765,5.409500,7.005650,5.488000,2.029500,0.492000,0.513000,0.499000,0.505500,0.515500
std,577.494589,12.614195,2.882415,2.011725,0.500015,1.70631,2.885129,2.846442,2.885484,1.432709,0.500061,0.499956,0.500124,0.500095,0.499885
min,1.000000,16.000000,2.000000,1.000000,0.000000,3.00000,1.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,500.750000,27.000000,4.500000,2.700000,0.000000,4.60000,3.000000,4.500000,3.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,1000.500000,38.000000,6.800000,4.400000,0.000000,6.00000,5.000000,7.100000,6.000000,2.000000,0.000000,1.000000,0.000000,1.000000,1.000000
75%,1500.250000,49.000000,9.400000,6.200000,1.000000,7.50000,8.000000,9.400000,8.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,2000.000000,59.000000,12.000000,8.000000,1.000000,9.00000,10.000000,12.000000,10.000000,4.000000,1.000000,1.000000,1.000000,1.000000,1.000000

info() gives details about columns, data types, and null values.

describe() provides statistical summary like mean, min, max, etc.

The dataset contains multiple numerical and categorical attributes.

### **Step 5: Attribute Description**
| Attribute                | Description           | Data Type |
| ------------------------ | --------------------- | --------- |
| Person_ID                | Unique ID             | int       |
| Age                      | Age of person         | int       |
| Gender                   | Male/Female           | object    |
| Occupation               | Student/Employed      | object    |
| Daily_Screen_Time        | Hours of screen usage | float     |
| Social_Media_Usage       | Social media hours    | float     |
| Night_Usage              | Device usage at night | int       |
| Sleep_Hours              | Daily sleep hours     | float     |
| Stress_Level             | Stress score          | int       |
| Work_Study_Hours         | Work/study time       | float     |
| Physical_Activity        | Activity level        | object    |
| Social_Interaction_Score | Interaction score     | int       |
| Caffeine_Intake          | Cups per day          | int       |
| Smoking                  | Yes/No (0/1)          | int       |
| Alcohol                  | Yes/No (0/1)          | int       |
| Depression               | Target (0/1)          | int       |
| Anxiety                  | Target (0/1)          | int       |
| Burnout                  | Target (0/1)          | int       |

### **Step 6: Check Missing Values**

In [ ]:
df.isnull().sum()

Person_ID                   0
Age                         0
Gender                      0
Occupation                  0
Daily_Screen_Time           0
Social_Media_Usage          0
Night_Usage                 0
Sleep_Hours                 0
Stress_Level                0
Work_Study_Hours            0
Physical_Activity           0
Social_Interaction_Score    0
Caffeine_Intake             0
Smoking                     0
Alcohol                     0
Depression                  0
Anxiety                     0
Burnout                     0
dtype: int64

### **Step 7: Remove Duplicates**

In [ ]:
df.drop_duplicates(inplace=True)

### **Step 8: Data Wrangling**
**Remove unnecessary column**

In [ ]:
df.drop('Person_ID', axis=1, inplace=True)

**Convert categorical data**

In [ ]:
df['Gender'] = df['Gender'].astype('category')
df['Occupation'] = df['Occupation'].astype('category')
df['Physical_Activity'] = df['Physical_Activity'].astype('category')

### **Step 9: Final Dataset**

In [ ]:
df.head()

,Age,Gender,Occupation,Daily_Screen_Time,Social_Media_Usage,Night_Usage,Sleep_Hours,Stress_Level,Work_Study_Hours,Physical_Activity,Social_Interaction_Score,Caffeine_Intake,Smoking,Alcohol,Depression,Anxiety,Burnout
0,54,Male,Student,10.2,7.5,0,6.5,8,5.8,Low,6,2,0,1,1,1,1
1,44,Male,Student,6.8,4.5,0,5.1,4,7.9,High,2,1,1,0,0,0,0
2,30,Male,Employed,5.5,6.9,0,3.5,10,9.4,Low,2,0,1,1,1,0,1
3,58,Male,Employed,5.6,4.1,0,9.0,2,2.0,High,10,0,0,1,0,0,0
4,23,Female,Employed,10.1,6.0,1,3.8,4,4.6,Low,4,4,0,1,1,1,0